#!/usr/bin/env php

<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yunwuxin <448901948@qq.com>
// +----------------------------------------------------------------------
// 定义配置文件目录和应用目录同级
//define('CONF_PATH', __DIR__.'/../config/');

define('ENV_PRODUCT', is_file(__DIR__ . '/.env.product'));

if(ENV_PRODUCT){
    define('CONF_PATH', __DIR__.'/config-product/');
} else {
    define('CONF_PATH', __DIR__.'/config/');
}

// 定义项目路径
define('APP_PATH', __DIR__ . '/application/');

// 加载框架引导文件
require __DIR__.'/thinkphp/console.php';
